"""renderhours

Revision ID: 33ad2d587d55
Revises: 8002682456c2
Create Date: 2025-07-18 15:10:50.346012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '33ad2d587d55'
down_revision: Union[str, None] = '8002682456c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'total')
    op.drop_column('booking', 'hours_rendered')
    op.add_column('services_list', sa.Column('hours_rendered', sa.Numeric(), nullable=False))
    op.alter_column('services_list', 'service_cost',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               nullable=True)
    op.add_column('transaction', sa.Column('total', sa.Numeric(precision=10, scale=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'total')
    op.alter_column('services_list', 'service_cost',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               nullable=False)
    op.drop_column('services_list', 'hours_rendered')
    op.add_column('booking', sa.Column('hours_rendered', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False))
    op.add_column('booking', sa.Column('total', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
