"""update client name

Revision ID: 8002682456c2
Revises: 38ac23b94dca
Create Date: 2025-07-18 12:53:04.897294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8002682456c2'
down_revision: Union[str, None] = '38ac23b94dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'booking', ['id'])
    op.add_column('clients', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('clients', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'clients', ['id'])
    op.drop_column('clients', 'name')
    op.create_unique_constraint(None, 'inventory', ['id'])
    op.create_unique_constraint(None, 'services', ['id'])
    op.create_unique_constraint(None, 'services_list', ['id'])
    op.create_unique_constraint(None, 'transaction', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='unique')
    op.drop_constraint(None, 'services_list', type_='unique')
    op.drop_constraint(None, 'services', type_='unique')
    op.drop_constraint(None, 'inventory', type_='unique')
    op.add_column('clients', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'last_name')
    op.drop_column('clients', 'first_name')
    op.drop_constraint(None, 'booking', type_='unique')
    # ### end Alembic commands ###
